name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup pnpm action
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.7

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
